CREATE TABLE `clients` (
	`id` varchar(36) NOT NULL,
	`organization_name` varchar(255) NOT NULL,
	`contact_person` varchar(255),
	`email` varchar(255),
	`phone` varchar(50),
	`address` text,
	`city` varchar(100),
	`state` varchar(100),
	`country` varchar(100),
	`pincode` varchar(20),
	`client_type` varchar(50),
	`registration_date` timestamp,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`gst_number` varchar(50),
	`pan_number` varchar(50),
	`credit_limit` decimal(10,2),
	`payment_terms` varchar(100),
	`assigned_sales_rep` varchar(36),
	`notes` text,
	`tags` json,
	CONSTRAINT `clients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `finance_records` (
	`id` varchar(36) NOT NULL,
	`sample_id` varchar(36),
	`lead_id` varchar(36),
	`invoice_number` varchar(100),
	`amount` decimal(10,2) NOT NULL,
	`tax_amount` decimal(10,2) DEFAULT '0',
	`total_amount` decimal(10,2) NOT NULL,
	`payment_status` varchar(50) DEFAULT 'pending',
	`payment_method` varchar(50),
	`payment_date` timestamp,
	`due_date` timestamp,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`currency` varchar(10) DEFAULT 'INR',
	`discount_amount` decimal(10,2) DEFAULT '0',
	`discount_reason` varchar(255),
	`billing_address` text,
	`billing_contact` varchar(255),
	`payment_terms` varchar(100),
	`late_fees` decimal(10,2) DEFAULT '0',
	`refund_amount` decimal(10,2) DEFAULT '0',
	`refund_reason` varchar(255),
	`notes` text,
	CONSTRAINT `finance_records_id` PRIMARY KEY(`id`),
	CONSTRAINT `finance_records_invoice_number_unique` UNIQUE(`invoice_number`)
);
--> statement-breakpoint
CREATE TABLE `lab_processing` (
	`id` varchar(36) NOT NULL,
	`sample_id` varchar(36) NOT NULL,
	`lab_id` varchar(100) NOT NULL,
	`qc_status` varchar(100),
	`dna_rna_quantity` decimal(8,2),
	`run_id` varchar(100),
	`library_prepared` boolean DEFAULT false,
	`sequencing_id` varchar(100),
	`is_outsourced` boolean DEFAULT false,
	`outsource_details` json,
	`processed_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`processed_by` varchar(36),
	`sample_type` varchar(100),
	`extraction_method` varchar(100),
	`concentration` decimal(8,2),
	`purity` decimal(5,2),
	`volume` decimal(8,2),
	`quality_score` varchar(50),
	`processing_notes` text,
	`equipment_used` varchar(255),
	`reagents` json,
	`processing_time` int,
	`temperature` decimal(5,2),
	`humidity` decimal(5,2),
	CONSTRAINT `lab_processing_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` varchar(36) NOT NULL,
	`organization` varchar(255) NOT NULL,
	`location` varchar(255) NOT NULL,
	`referred_doctor` varchar(255) NOT NULL,
	`clinic_hospital_name` varchar(255),
	`phone` varchar(50) NOT NULL,
	`email` varchar(255) NOT NULL,
	`client_email` varchar(255) NOT NULL,
	`test_name` varchar(255) NOT NULL,
	`sample_type` varchar(255) NOT NULL,
	`amount_quoted` decimal(10,2) NOT NULL,
	`tat` int NOT NULL,
	`status` varchar(50) DEFAULT 'quoted',
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`created_by` varchar(36),
	`converted_at` timestamp,
	`category` varchar(50) DEFAULT 'clinical',
	`discovery_organization` varchar(255),
	`clinician_name` varchar(255),
	`specialty` varchar(255),
	`clinician_org_email` varchar(255),
	`clinician_org_phone` varchar(50),
	`service_name` varchar(255),
	`pickup_from` varchar(255),
	`delivery_upto` varchar(255),
	`discovery_status` varchar(100),
	`follow_up` varchar(255),
	`lead_type_discovery` varchar(100),
	`budget` decimal(10,2),
	`sample_shipment_amount` decimal(10,2),
	`no_of_samples` int,
	`patient_client_name` varchar(255),
	`age` int,
	`gender` varchar(20),
	`patient_client_phone` varchar(50),
	`patient_client_email` varchar(255),
	`sales_responsible_person` varchar(255),
	`date_sample_received` timestamp,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `logistics_tracking` (
	`id` varchar(36) NOT NULL,
	`sample_id` varchar(36),
	`tracking_number` varchar(100),
	`courier_name` varchar(100),
	`pickup_date` timestamp,
	`estimated_delivery` timestamp,
	`actual_delivery` timestamp,
	`status` varchar(50) DEFAULT 'scheduled',
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`pickup_address` text,
	`delivery_address` text,
	`contact_person` varchar(255),
	`contact_phone` varchar(50),
	`special_instructions` text,
	`package_weight` decimal(8,2),
	`package_dimensions` varchar(100),
	`insurance_amount` decimal(10,2),
	`shipping_cost` decimal(10,2),
	`tracking_updates` json,
	`delivery_notes` text,
	CONSTRAINT `logistics_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` varchar(36) NOT NULL,
	`user_id` varchar(36),
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`type` varchar(100) NOT NULL,
	`is_read` boolean DEFAULT false,
	`related_id` varchar(36),
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pricing` (
	`id` varchar(36) NOT NULL,
	`test_name` varchar(255) NOT NULL,
	`test_code` varchar(50),
	`base_price` decimal(10,2) NOT NULL,
	`discounted_price` decimal(10,2),
	`currency` varchar(10) DEFAULT 'INR',
	`is_active` boolean DEFAULT true,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`category` varchar(100),
	`subcategory` varchar(100),
	`description` text,
	`turnaround_time` int,
	`sample_requirements` text,
	`methodology` varchar(255),
	`accreditation` varchar(255),
	`valid_from` timestamp,
	`valid_to` timestamp,
	`notes` text,
	CONSTRAINT `pricing_id` PRIMARY KEY(`id`),
	CONSTRAINT `pricing_test_code_unique` UNIQUE(`test_code`)
);
--> statement-breakpoint
CREATE TABLE `reports` (
	`id` varchar(36) NOT NULL,
	`sample_id` varchar(36) NOT NULL,
	`status` varchar(50) DEFAULT 'in_progress',
	`report_path` varchar(500),
	`generated_at` timestamp,
	`approved_at` timestamp,
	`approved_by` varchar(36),
	`delivered_at` timestamp,
	`report_type` varchar(100),
	`report_format` varchar(50),
	`findings` text,
	`recommendations` text,
	`clinical_interpretation` text,
	`technical_notes` text,
	`quality_control` json,
	`validation_status` varchar(50),
	`report_version` varchar(20),
	`delivery_method` varchar(50),
	`recipient_email` varchar(255),
	CONSTRAINT `reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sales_activities` (
	`id` varchar(36) NOT NULL,
	`lead_id` varchar(36),
	`activity_type` varchar(50) NOT NULL,
	`description` text,
	`outcome` varchar(100),
	`next_action` varchar(255),
	`scheduled_date` timestamp,
	`completed_date` timestamp,
	`assigned_to` varchar(36),
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`duration` int,
	`priority` varchar(50),
	`status` varchar(50) DEFAULT 'planned',
	`notes` text,
	`attachments` json,
	CONSTRAINT `sales_activities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `samples` (
	`id` varchar(36) NOT NULL,
	`sample_id` varchar(64) NOT NULL,
	`lead_id` varchar(36) NOT NULL,
	`status` varchar(50) DEFAULT 'pickup_scheduled',
	`courier_details` json,
	`amount` decimal(10,2) NOT NULL,
	`paid_amount` decimal(10,2) DEFAULT '0',
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `samples_id` PRIMARY KEY(`id`),
	CONSTRAINT `samples_sample_id_unique` UNIQUE(`sample_id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` varchar(36) NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`password` varchar(255) NOT NULL,
	`role` varchar(100) NOT NULL,
	`is_active` boolean DEFAULT true,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`last_login` timestamp,
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`)
);
