USE leadlab_lims;

-- Migration: create project_samples table to match frontend/back-end fields
CREATE TABLE IF NOT EXISTS project_samples (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id VARCHAR(100) NULL,
    sample_id VARCHAR(100) NULL,
    unique_id VARCHAR(255) UNIQUE NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    sample_collected_date DATETIME NULL,
    sample_received_date DATETIME NULL,
    sample_shipped_date DATETIME NULL,
    lead_type VARCHAR(100) NULL,
    status VARCHAR(100) DEFAULT 'new',
    genetic_counsellor_required BOOLEAN DEFAULT FALSE,
    created_by VARCHAR(255) NULL,
    sales_responsible_person VARCHAR(255) NULL,
    gender VARCHAR(50) NULL,
    service_name VARCHAR(255) NULL,
    nutrition_management VARCHAR(255) NULL,
    sample_type VARCHAR(255) NULL,
    organisation_hospital VARCHAR(255) NULL,
    clinician_researcher_name VARCHAR(255) NULL,
    speciality VARCHAR(255) NULL,
    clinician_researcher_email VARCHAR(255) NULL,
    clinician_researcher_contact VARCHAR(100) NULL,
    patient_client_name VARCHAR(255) NULL,
    age INT NULL,
    patient_client_email VARCHAR(255) NULL,
    patient_client_contact VARCHAR(100) NULL,
    no_of_samples INT NULL,
    budget DECIMAL(12,2) NULL,
    follow_up DATETIME NULL,
    sample_pickup_from VARCHAR(500) NULL,
    delivery_upto DATETIME NULL,
    sample_shipment_amount DECIMAL(12,2) NULL,
    tracking_id VARCHAR(255) NULL,
    courier_company VARCHAR(255) NULL,
    progenics_trf VARCHAR(255) NULL,
    phlebotomist_charges DECIMAL(12,2) NULL,
    patient_address TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
