-- 0016_create_logistic_sheet.sql
-- Migration: create logistic_sheet table

CREATE TABLE IF NOT EXISTS `logistic_sheet` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `unique_id` VARCHAR(80) NOT NULL,
  `project_id` VARCHAR(80) NOT NULL,
  `sample_collection_date` DATE NULL,
  `sample_shipped_date` DATE NULL,
  `sample_delivery_date` DATE NULL,
  `sample_pick_up_from` VARCHAR(255) NULL,
  `delivery_up_to` VARCHAR(255) NULL,
  `tracking_id` VARCHAR(120) NULL,
  `courier_company` VARCHAR(200) NULL,
  `sample_shipment_amount` DECIMAL(10,2) NULL,
  `organisation_hospital` VARCHAR(255) NULL,
  `clinician_researcher_name` VARCHAR(200) NULL,
  `clinician_researcher_phone` VARCHAR(60) NULL,
  `patient_client_name` VARCHAR(200) NULL,
  `patient_client_phone` VARCHAR(60) NULL,
  `sample_received_date` DATE NULL,
  `sales_responsible_person` VARCHAR(200) NULL,
  `third_party_name` VARCHAR(200) NULL,
  `third_party_phone` VARCHAR(60) NULL,
  `sample_sent_to_third_party_date` DATE NULL,
  `sample_received_from_third_party_date` DATE NULL,
  `alert_to_labprocess_team` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` VARCHAR(80) NULL,
  `remark_comment` TEXT NULL,
  UNIQUE KEY `ux_logistic_unique_id` (`unique_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_tracking_id` (`tracking_id`),
  KEY `idx_organisation_hospital` (`organisation_hospital`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
